version: "3.9"

volumes:
  static:
  media:

networks:
  webnet:

services:
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - ./backend:/app:delegated
      - static:/app/collected_static
      - media:/app/media
    command: >
      sh -c "
        echo 'Collecting static...' &&
        python manage.py collectstatic --noinput --clear &&
        echo 'Starting Gunicorn...' &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
        --workers 2 --threads 4 --timeout 60
        --access-logfile - --error-logfile -"
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks: [webnet]

  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles:ro
      - media:/mediafiles:ro
    depends_on:
      - backend
    ports:
      - "8000:80"
    restart: unless-stopped
    networks: [webnet]