# Generated by Django 4.2.27 on 2026-01-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Car Category",
                "verbose_name_plural": "Car Categories",
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                ("main_image", models.URLField(max_length=500)),
                ("image_2", models.URLField(blank=True, max_length=500)),
                ("image_3", models.URLField(blank=True, max_length=500)),
                ("image_4", models.URLField(blank=True, max_length=500)),
                ("seats", models.PositiveIntegerField(default=2)),
                ("transmission", models.CharField(default="Automatic", max_length=50)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated: Exclusive, Hybrid, Sport",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="core.carcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
