# Generated by Django 4.2.23 on 2025-08-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReviewImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("tripadvisor", "TripAdvisor"),
                            ("fallback", "Fallback"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("reviews_imported", models.IntegerField(default=0)),
                ("reviews_updated", models.IntegerField(default=0)),
                ("reviews_skipped", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("tripadvisor", "TripAdvisor"),
                            ("fallback", "Fallback"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("author_name", models.CharField(max_length=255)),
                ("author_photo_url", models.URLField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                    ),
                ),
                ("text", models.TextField()),
                ("review_date", models.DateTimeField()),
                (
                    "relative_time_description",
                    models.CharField(blank=True, max_length=100),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-is_featured", "-review_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "is_active"],
                        name="core_review_source_40aea1_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "is_active"],
                        name="core_review_is_feat_23cd72_idx",
                    ),
                    models.Index(
                        fields=["review_date"], name="core_review_review__affdb7_idx"
                    ),
                ],
            },
        ),
    ]
