# Generated by Django 4.2.24 on 2025-09-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_create_reviews_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Краткий заголовок отзыва, например: 'Take this tour! Its fantastic!'",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reviewimportlog",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reviewimportlog",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewimportlog",
            name="import_settings",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewimportlog",
            name="total_rows_processed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewimportlog",
            name="warnings",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="source",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("tripadvisor", "TripAdvisor"),
                    ("csv_import", "CSV Import"),
                    ("fallback", "Fallback"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reviewimportlog",
            name="source",
            field=models.CharField(
                choices=[
                    ("google", "Google Places"),
                    ("tripadvisor", "TripAdvisor"),
                    ("csv_import", "CSV Import"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reviewimportlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="running",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["external_id"], name="core_review_externa_ac882c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewimportlog",
            index=models.Index(
                fields=["source", "status"], name="core_review_source_702fc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewimportlog",
            index=models.Index(
                fields=["started_at"], name="core_review_started_106238_idx"
            ),
        ),
    ]
