# Generated by Django 4.2.27 on 2026-01-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="GTM, Google Ads, Meta Pixel, etc.", max_length=200
                    ),
                ),
                ("code", models.TextField(help_text="Paste your code here")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("head_start", "Head - Start"),
                            ("head_end", "Head - End"),
                            ("body_start", "Body - Start (after <body>)"),
                            ("body_end", "Body - End (before </body>)"),
                            ("footer", "Footer Section"),
                        ],
                        default="head_end",
                        max_length=20,
                    ),
                ),
                (
                    "snippet_type",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("js", "JavaScript"),
                            ("css", "CSS"),
                        ],
                        default="html",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(default=10, help_text="Lower = loads first"),
                ),
                ("show_on_all_pages", models.BooleanField(default=True)),
                (
                    "show_on_urls",
                    models.TextField(
                        blank=True, help_text="One URL per line, e.g. /contacts/"
                    ),
                ),
                (
                    "exclude_urls",
                    models.TextField(blank=True, help_text="Exclude these URLs"),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Code Snippet",
                "verbose_name_plural": "Code Snippets",
                "ordering": ["location", "priority", "name"],
            },
        ),
    ]
