# Generated by Django 4.2.27 on 2026-01-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_codesnippet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="car",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
    ]
